dist: trusty
language: php
sudo: required

php:
    - 7.1
    - 7.2
    - nightly

before_install:
    - composer self-update

before_script:
    - travis_retry composer update --prefer-dist

script: ./vendor/bin/phpunit

jobs:
    include:
        -   stage: Code Quality
            env: CODING_STANDARD
            php: 7.1
            script:
                - ./vendor/bin/phpcs

        -   stage: Code Quality
            env: STATIC_ANALYSIS
            php: 7.1
            script:
                - ./vendor/bin/phpstan analyse

cache:
    directories:
        - $HOME/.composer/cache

after_script:
    # upload clover.xml file to Scrutinizer to analyze it
    - |
        if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
        if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover temp/clover.xml; fi
